require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  Exclude:
   - 'bin/**/*'
   - 'config/**/*'
   - 'db/**/*'
   - 'test/**/*'
   - 'vendor/**/*'
   - 'spec/rails_helper.rb'

Documentation:
 Enabled: false

Metrics/BlockLength:
 Exclude:
  - "spec/**/*"

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for  

Style/FrozenStringLiteralComment:
 Enabled: false  

Style/StringLiterals:
  EnforcedStyle: double_quotes